### ISSUE TITLE
태블릿 모드 레이아웃에서 고민 글을 수정할 때, "수정 완료"가 눌러지지 않는 현상

### ISSUE THREAD

**Issue by colab-taewoo** [osamhack2022/WEB_WhisperSoldier_ReSoldier#10]
태블릿 모드 레이아웃에서 고민 글을 수정하고 "수정 완료" 버튼을 누를 때, "수정하시겠습니까?" 안내 창 대신에 아무 반응이 없습니다.
모바일과 PC 모드에서는 "수정 완료"가 이상 없이 눌러집니다.
태블릿 모드의 화면을 첨부합니다.
![image](https://user-images.githubusercontent.com/109520501/198867843-09962b66-1422-43b3-ad0b-98b294779c69.png)

**Comment by galaxy821** [comment]
포스트 수정할때 alert 위치를 수정하여 버튼 클릭을 가능하게 조치함
https://github.com/osamhack2022/WEB_WhisperSoldier_ReSoldier/commit/f920645fc20e1e0ee42ea847f8067944517cef4f
