### ISSUE TITLE
고민글 길이에 따라 홈페이지 레이아웃이 변하는 현상

### ISSUE THREAD

**Issue by colab-taewoo** [osamhack2022/WEB_WhisperSoldier_ReSoldier#9]
홈페이지에 최신 게시판, 인기 게시판은 상위 5개 포스트를 불러옵니다. 이 상위 5개 고민 포스트 모두 길이가 짧을 경우 페이지 레이아웃이 변하는 현상이 발생합니다. 관련 이미지를 첨부합니다.
![image](https://user-images.githubusercontent.com/109520501/198858420-421c9ea6-6757-4db3-a51d-b9f744c6acf4.png)

**Comment by galaxy821** [comment]
레이아웃 속성 변경으로 해결했습니다.
